config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "password", to: "password#new"
  patch "password", to: "password#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "register", to: "registration#new"
  post "register", to: "registration#create"

  get "about", to: "about#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id]) 
        end
    end

    def require_user_logged_in!
        redirect_to login_path, :flash => { :warning => "Please login first" } if Current.user.nil?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comments = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
    before_action :require_user_logged_in!

    def new
    end
    
    def update
        if !Current.user.authenticate(password_params[:current_password])
            redirect_to password_path, :flash => { :danger => "Current password is invalid" }
        elsif Current.user.update(:password => password_params[:password], :password_confirmation => password_params[:password_confirmation])
            redirect_to root_path, :flash => {:success => "Password updated"}
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
    def password_params
        params.require(:user).permit(:current_password, :password, :password_confirmation)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            # Send email
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to password_reset_path, :flash => { :success => "If an account with that email was found, we have sent a link to reset your password." }
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "reset_password")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to login_path, :flash => { :warning => "Your token has expired. Please try again." }
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "reset_password")
        if @user.update(password_params)
            redirect_to login_path, :flash => { :success => "Your password was reset successfully." }
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, :flash => { :success => "Successfully created account" } 
        else
             render :new, status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        if Current.user
            redirect_to root_path
        end
    end

    def create
        user = User.find_by(email: params[:email]) 
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, :flash => { :success => "Logged in successfully" }
        else
            flash.now[:warning] = "Email or password incorrect"
            render :new,  status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, :flash => { :success => "Logged out successfully" }
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/views/about/index.html.erb
<h1 class="d-flex align-items-center justify-content-center">
  About Us
</h1>

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end  %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Form</h1>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<ul>
  <%@articles.each do |article|%>
    <li>
      <%= link_to article.title, article %>
    </li>
  <%end%>
</ul>
<%= link_to "Create new article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Form</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>Article: <%= @article.title %></h1>
<h5>Body: <%= @article.body%></h5>
<ul>
  <li><%= link_to "Edit",  edit_article_path(@article) %></li>
  <li>
    <%= link_to "Delete", article_path(@article), data: {
        turbo_method: :delete, turbo_confirm: "Are you sure?"
    } %>
  </li>
</ul>
<h2>Comments</h2>
<%= render @article.comments %>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.commenter %>: </strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link as="style" rel="stylesheet preload prefetch" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex justify-content-center">
  <h1>
    Welcome to scheduled tweets
  </h1>
</div>

app/views/password/new.html.erb
<h1>Update Password</h1>
<%= form_with model: Current.user, url: password_path do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label "Current Password", class: "form-label" %>
    <%= form.password_field :current_password, class: "form-control", placeholder: "Enter current password", required: true %>
  </div>
  <div class="mb-3">
    <%= form.label "New Password", class: "form-label" %>
    <%= form.password_field :password, class: "form-control", placeholder: "Enter new password", required: true %>
  </div>
  <div class="mb-3">
    <%= form.label "New Password Confirm", class: "form-label" %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Enter new password again", required: true %>
  </div>
  <%= form.submit "Update", class: "btn btn-secondary" %>
<% end %>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label "Enter new password", class: "form-label" %>
    <%= form.password_field :password, class: "form-control", placeholder: "Enter new password here" %>
  </div>
  <div class="mb-3">
    <%= form.label "Confirm new password", class: "form-label" %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Enter new password again" %>
  </div>
  <%= form.submit "Reset Password", class: "btn btn-secondary" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>
<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
    <%= form.label "Enter email associated with your account", class: "form-label" %>
    <%= form.email_field :email, class: "form-control", placeholder: "john@stjude.com", required: true %>
  </div>
  <%= form.submit "Reset Password", class: "btn btn-secondary" %>
<% end %>

app/views/shared/_close_button.html.erb
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:success] %>
    <%= render partial: "shared/close_button" %>
  </div>
<% end %>
<% if flash[:info] %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= flash[:info] %>
    <%= render partial: "shared/close_button" %>
  </div>
<% end %>
<% if flash[:warning] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:warning] %>
    <%= render partial: "shared/close_button" %>
  </div>
<% end %>
<% if flash[:danger] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:danger] %>
    <%= render partial: "shared/close_button" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Ruby", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_path, class: "nav-link" %>
        </li>
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to "Articles", articles_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><span class="dropdown-item disabled"><%= Current.user.email %></span></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Update Password", password_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", register_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>